Traceback (most recent call last):
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Faramarzigroup\Desktop\aparatcomenterstable\commenter0.1.py", line 4, in <module>
    driver = webdriver.Firefox()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 300, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 321, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\_request_methods.py", line 118, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\poolmanager.py", line 444, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1322, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1081, in _send_output
    self.send(msg)
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1025, in send
    self.connect()
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\connection.py", line 81, in create_connection
    sock.close()
  File "C:\Users\Faramarzigroup\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 500, in close
    def close(self):

KeyboardInterrupt
